Change the way how / is stored in dirindex
Previously, / was stored in dirindex with leading slash (i.e. as //)
what caused various side effects as:

filesystem-4.0-12.x86_64 obsoleted by filesystem-4.0-13.x86_64
filesystem-4.0-13.x86_64 marks FHS-2.3-35.x86_64 (cap //)
error: FHS-2.3-35.x86_64: equal version installed, give up